INSERT INTO PAIS(nombre) VALUES ('Argentina');
INSERT INTO PAIS(nombre) VALUES ('Bolivia');
INSERT INTO PAIS(nombre) VALUES ('Brasil');
INSERT INTO PAIS(nombre) VALUES ('Chile');
INSERT INTO PAIS(nombre) VALUES ('Colombia');
INSERT INTO PAIS(nombre) VALUES ('Costa Rica');
INSERT INTO PAIS(nombre) VALUES ('Cuba');
INSERT INTO PAIS(nombre) VALUES ('Ecuador');
INSERT INTO PAIS(nombre) VALUES ('El Salvador');
INSERT INTO PAIS(nombre) VALUES ('Guayana Francesa');
INSERT INTO PAIS(nombre) VALUES ('Granada');
INSERT INTO PAIS(nombre) VALUES ('Guatemala');
INSERT INTO PAIS(nombre) VALUES ('Guayana');
INSERT INTO PAIS(nombre) VALUES ('Haití');
INSERT INTO PAIS(nombre) VALUES ('Honduras');
INSERT INTO PAIS(nombre) VALUES ('Jamaica');
INSERT INTO PAIS(nombre) VALUES ('México');
INSERT INTO PAIS(nombre) VALUES ('Nicaragua');
INSERT INTO PAIS(nombre) VALUES ('Paraguay');
INSERT INTO PAIS(nombre) VALUES ('Panamá');
INSERT INTO PAIS(nombre) VALUES ('Perú');
INSERT INTO PAIS(nombre) VALUES ('Puerto Rico');
INSERT INTO PAIS(nombre) VALUES ('República Dominicana');
INSERT INTO PAIS(nombre) VALUES ('Surinam');
INSERT INTO PAIS(nombre) VALUES ('Uruguay');
INSERT INTO PAIS(nombre) VALUES ('Venezuela'); 